security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

github:
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user



weibo:
  client:
    clientId: 3050804627
    clientSecret: bf408e0747d07bd683599e6f539b61df
    accessTokenUri: https://api.weibo.com/controller/access_token
    userAuthorizationUri: https://api.weibo.com/controller/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.weibo.com/user

logging:
  level:
    org.springframework.security: DEBUG